openapi: 3.0.0
info:
  title: Post API
  description: This api is used for Post Service.
  version: 0.1.9
servers:
  - url: http://localhost:8081/blog/v1/api/
    description: url de serveur de développement  
paths:
  /posts:
    get:
      summary: Retourne une liste de posts
      description: Description optionnelle
      responses:
        '200':    # status code
          description: Tableau json des posts
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string